// This is a temporary file that generates lorem
// text for assigned tags. Be sure to remove it
// from the bottom of your HTML page to ensure 
// no errors will occur in your page.

let str = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at nulla tristique elit vehicula tincidunt at sed lorem. Maecenas efficitur ligula et dolor porttitor aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur feugiat a velit in semper. Cras purus velit, pellentesque vitae bibendum vel, euismod id magna. Integer venenatis vel sapien eget scelerisque. Vivamus ut elementum diam. Nam est mi, condimentum eget elementum in, mollis eget dui. Nunc accumsan purus sed risus porta condimentum. Fusce ac nunc sit amet est volutpat tristique. Quisque congue sagittis elit vel condimentum. Pellentesque eget eros non sapien bibendum ullamcorper. Praesent in massa aliquam, tincidunt sapien nec, pulvinar augue. Pellentesque posuere ornare consectetur. Aliquam ac aliquet dolor, nec elementum ex. Vestibulum massa magna, consequat vel lobortis facilisis, efficitur sed ex. Curabitur at purus tortor. Sed porttitor rhoncus pellentesque. Suspendisse potenti. Fusce non leo lobortis, porttitor dolor eget, commodo nisl. Vestibulum vestibulum accumsan fermentum. Aliquam eu libero scelerisque, varius risus id, malesuada erat. Aliquam a ipsum sit amet tortor rutrum fringilla ac a lectus. Morbi quis rutrum lectus, in maximus mauris. Praesent vestibulum tortor vitae venenatis iaculis. Cras turpis nisi, facilisis eu massa vitae, ornare aliquet dui. In hac habitasse platea dictumst. Aenean interdum non enim non tincidunt. Aliquam ac enim vitae urna aliquam tristique sed eu metus. Ut at odio vel justo consequat pulvinar. Curabitur a varius tortor. Integer at dolor viverra orci euismod dictum. Etiam in enim at leo mollis aliquet vitae vulputate quam. Morbi vehicula nunc in nisi pulvinar luctus. Aenean laoreet fermentum nisi, ut ullamcorper mauris consequat a. Morbi nec ipsum mi. Morbi in faucibus neque, cursus luctus ligula. Vivamus velit tellus, congue sit amet luctus non, dignissim eget nibh. Pellentesque venenatis viverra metus, vel mattis sem aliquam nec. Sed ultricies fringilla accumsan. Suspendisse potenti. Nulla dignissim nec turpis quis varius. Nam ac laoreet metus, at mollis ligula. Duis porttitor varius pellentesque. Suspendisse arcu massa, mattis quis erat fringilla, porttitor suscipit dui. Maecenas dignissim vehicula magna. Quisque sit amet magna eu leo hendrerit vestibulum. Integer sagittis tortor eget lorem scelerisque tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;';

let lorem = document.getElementsByClassName('lorem');

for(i=0; i!=lorem.length; i++)
{
    lorem[i].innerText = str;
}